#####################################################################################
# Referenced: https://techcommunity.microsoft.com/t5/microsoft-security-copilot-blog/using-microsoft-graph-as-a-microsoft-copilot-for-security-plugin/ba-p/4198148
#
# Within Entra - Register a new Application e.g.
#   Name: CfS Plugin GraphAPI GroupManagement Audits
#   Redirect URI = https://api.securitycopilot.microsoft.com/
#   API Permissions (delegated):
#       AuditLog.Read.All
#       Directory.Read.All
#
#	
# https://developer.microsoft.com/en-us/graph/graph-explorer
#####################################################################################
# Updated 2024-10-08

openapi: 3.0.0

info:
    title: GraphAPI GroupManagement audits
    description: Skills demo associated with requestion information via Graph API calls with OData filters
    version: "v1"

servers:
    - url: https://graph.microsoft.com/v1.0

paths:

#####################################################################################
# https://learn.microsoft.com/en-us/graph/api/directoryaudit-list
#	AuditLog.Read.All
#	Directory.Read.All
#
# https://learn.microsoft.com/en-us/entra/identity/monitoring-health/reference-audit-activities
#	Audit Category: GroupManagement
#####################################################################################
    /auditLogs/directoryAudits?$filter=category eq 'GroupManagement':
        get:
            operationId: GetAllDirectoryAudits
            description: |
              Gets all group management audits from the DirectoryAudits 
              #ExamplePrompt: Gets all group management audits from the DirectoryAudits 
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
