#####################################################################################
# Referenced: https://techcommunity.microsoft.com/t5/microsoft-security-copilot-blog/using-microsoft-graph-as-a-microsoft-copilot-for-security-plugin/ba-p/4198148
#
# Within Entra - Register a new Application e.g.
#   Name: CfS Plugin GraphAPI GroupManagement Audits
#   Redirect URI = https://api.securitycopilot.microsoft.com/
#   API Permissions (delegated):
#       AuditLog.Read.All
#       Directory.Read.All
#
#	
# https://developer.microsoft.com/en-us/graph/graph-explorer
#####################################################################################
# Updated 2024-10-08

openapi: 3.0.0

info:
    title: GraphAPI GroupManagement audits
    description: Skills demo associated with requestion information via Graph API calls with OData filters
    version: "v1"

servers:
    - url: https://graph.microsoft.com/v1.0

paths:

#####################################################################################
# https://learn.microsoft.com/en-us/graph/api/directoryaudit-list
#	AuditLog.Read.All
#	Directory.Read.All
#
# https://learn.microsoft.com/en-us/entra/identity/monitoring-health/reference-audit-activities
#	Audit Category: GroupManagement
#####################################################################################
    /auditLogs/directoryAudits?$filter=category eq 'GroupManagement':
        get:
            operationId: GetAllDirectoryAudits
            description: |
              Gets all group management audits from the DirectoryAudits 
              #ExamplePrompt: Gets all group management audits from the DirectoryAudits 
            responses:
                "200":
                    description: OK
                    content:
                        application/json:

#####################################################################################
# Get call using the 'query' parameter.
#####################################################################################

    /security/alerts_v2?$select=id,title:
        get:
            operationId: testGetAlertIdsFromIncidentId
            description: |
              List all alert ID's based on a user provided Incident ID
              #ExamplePrompt: show me alert ids for the specified incident id
              #ExamplePrompt: Get me all alert ids where incident id is provided
            parameters:
#             Parameters can be be denoted as 'path', 'query, 'header', or 'cookie'. For most situations you'll simply need to denote "path" or "query"
                - in: query
#                     Query parameters will result in appending "&filter=" along with the string. 
#                       In this example if the string submitted was 'office.com' would result in https://graph.microsoft.com/v1.0/security/alerts_v2?$select=id,title&filter=incidentid eq '16'
                  name: $filter
                  schema:
                      type: string
                  required: true
                  description: Enter the the string "incidentid eq 'ID'" and modify ID to denote the Incident ID you're looking up. (e.g. incidentid eq '16' )
            responses:
                "200":
                    description: OK
                "400":
                    description: Bad request, invalid parameters
                "401":
                    description: Unauthorized, API key missing or invalid
                "403":
                    description: Forbidden, access to the resource is denied

#####################################################################################
# Get call using the 'path' parameter.
#####################################################################################
   /security/alerts_v2/{alertid}?$select=evidence:
        get:
            operationId: testGetEvidenceForSpecificAlert
            description: |
              Get all the evidence details of a specific alert id
              #ExamplePrompt: Get all the evidence details for alert ID 1234
            parameters:
#             Parameters can be be denoted as 'path', 'query, 'header', or 'cookie'. For most situations you'll simply need to denote "path" or "query"
                - in: path
#                    asdf   {alertid}
#                     Path parameters that are part of the URL path, such as /security/alerts_v2/{alertid}.
#                       In this example, if the alert ID of d65sg8f1-d0cd-4d7d-8c6c-d1821138 was submitted the submitted result would be https://graph.microsoft.com/v1.0/security/alerts_v2/d65sg8f1-d0cd-4d7d-8c6c-d1821138?$select=evidence
                  name: alertid
                  schema:
                      type: string
                  required: true
                  description: id of the alert