# This example API key auth plugin template using the VirusTotal API as an example to illustrate GET and POST calls
# Updated 2024-10-08

openapi: 3.0.0

info:
    title: Example API key auth plugin template using VirusTotal
    description: Example API key auth plugin template using VirusTotal - 2024-10-08
    version: "v1.0.0"
    
servers:
    - url: https://www.virustotal.com/api/v3
#          Root API URL that will be used for all subsequent GET and POST API calls below
paths:

####################################################################################
# - API 'get' request example with "path" parameter
####################################################################################
# IOC Reputation & Enrichment
#   IP addresses
#       Get an IP address report
#       https://docs.virustotal.com/reference/ip-info
####################################################################################

    /ip_addresses/{ip}:
        get:
#           Copilot for Security only supports GET and POST requests
            operationId: VT-IPReport
            description: |
              VirusTotal - Used to assess the reputation and threat level of a provided IP addresses.
              This area can be multiple lines when using the pipe character after the colon character.
              You'll want to include additional information that is relevant for the Orchestreator to understand
              #ExamplePrompt Get an IP report using VirusTotal for this IP address
              #ExamplePrompt You'll want to include a few examples so the Orchestrator understands how to map user requests to the skill
            parameters:
#             Parameters can be of the following types. For most situations you'll simply need to denote "path" or "query"
                - in: path
#                     Path parameters that are part of the URL path, such as /ip_addresses/{ip}.
#                       In this example, if the IP 216.239.36.21 is submitted the submitted result would be https://www.virustotal.com/api/v3/ip_addresses/216.239.36.21
                  name: ip
                  schema:
                      type: string
                  required: true
                  description: IP address to look up (e.g. 216.239.36.21)
            responses:
                "200":
                    description: OK
                "400":
                    description: Bad request, invalid parameters

					
####################################################################################
# - API 'get' request example with "query" parameter
####################################################################################
# IOC Reputation & Enrichment
#   Search & Metadata
#      Search for files, URLs, domains, IPs, and comments 
#       https://docs.virustotal.com/reference/api-search
####################################################################################
    /search:
        get:
            operationId: VT-SearchForFilesURLsDomainsAndComments
            description: |
               VirusTotal - Search for files, URLs, domains, IPs and comments
               Helps to search for indicators of compromise across various categories.
            parameters:
                - in: query
                  name: query
#                     Query: Parameters that are appended to the URL after a question mark, such as /users?id=1234.
#                       In this case if the string submitted was 'office.com' would result in https://docs.virustotal.com/reference/api-search?query=office.com
                  schema:
                      type: string
                  required: true
                  description: Enter in a file hash, URL, domain, IP, or comments that you want to search for.
            responses:
                "200":
                    description: OK
                "400":
                    description: Bad request, invalid parameters



####################################################################################
# - API 'post' request example
####################################################################################
# IOC Reputation & Enrichment
#   URLs
#       Scan URL
#       https://docs.virustotal.com/reference/scan-url
####################################################################################
    /urls:
        post:
            operationId: VT-ScanURL
            description: |
              Submit a URL for scanning - returns an Analysis ID.
              VirusTotal - Submit a URL for scanning - returns an Analysis ID.
            requestBody:
              required: true
              content:
                application/x-www-form-urlencoded:
                  schema:
                    type: object
                    properties:
                      url:
                        type: string
                        description: The URL to be scanned (e.g. www.virustotal.com).
                        example: "http://www.virustotal.com"
                    required:
                      - url
            responses:
              '200':
                description: Scan initiated successfully.
                content:
                  application/json:
                    schema:
#                       While this section describing the scheme isn't required, it does help Copilot for Secuity to better understand and format the output.                    
                      type: object
                      properties:
                        data:
                          type: object
                          properties:
                            type:
                              type: string
                              example: "url"
                            id:
                              type: string
                              description: The Analysis ID for the URL scan is.
                              example: "u-a354494a73382ea0b4bc47f4c9e8d6c578027cd4598196dc88f05a22b5817293-1725740919"
                            links:
                              type: object
                              properties:
                                self:
                                  type: string
                                  description: The URL for retrieving the scan results.
                                  example: "https://www.virustotal.com/api/v3/urls/1f0b6e03ce451b4325dd2b67192c9b7e"
                "400":
                    description: Bad request, invalid parameters
