openapi: 3.0.0

info:
  title: ADX Query Plugin
  description: A plugin to query data from an Azure Data Explorer (ADX) cluster.
  version: 1.0.0

servers:
  - url: https://alpine-cluster01.eastus.kusto.windows.net/v1/rest

paths:
  /query:
    post:
      summary: Execute KQL query in ADX
      description: Makes a POST request to an ADX cluster to run a Kusto Query Language (KQL) query.
      operationId: executeKQLQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                db:
                  type: string
                  example: "YourDatabaseName"
                csl:
                  type: string
                  example: "GCPAuditLogs | sort by TimeGenerated desc | take 10"
      responses:
        '200':
          description: Query executed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Tables:
                    type: array
                    items:
                      type: object
                      properties:
                        TableName:
                          type: string
                        Columns:
                          type: array
                          items:
                            type: object
                            properties:
                              ColumnName:
                                type: string
                              DataType:
                                type: string
                        Rows:
                          type: array
                          items:
                            type: array
                            description: Query results, row by row
        '400':
          description: Bad request, invalid input.
        '401':
          description: Unauthorized access, invalid token.
        '500':
          description: Internal server error.
