# Author Rick Kotlarz ~ https://github.com/RickKotlarz/
# 2024-Dec-26
#
# https://cortex-panw.stoplight.io/docs/cortex-xsoar-8/

openapi: 3.0.0

info:
  title: Palo Alto XSOAR
  description: Plugin example leveraging the Palo Alto XSOAR API
  version: "v1.0.2"
    
servers:
  - url:  https://httpbin.org/
#  - url: https://api-yourfqdn/xsoar/
#   Replace the above URL with your Palo Alto XSOAR URL.

# https://learn.openapis.org/specification/security.html
components:
  securitySchemes:
    apiKeyIDAuth:              # arbitrary name for the security scheme
      type: apiKey
      in: header               # can be "header", "query" or "cookie"
      name: x-xdr-auth-id      # Value sent to the endpoint in the requested (e.g. {x-xdr-auth-id: 24})
      description: "The API Key ID for authentication."
    apiKeySecretAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "The API Key Secret for authentication."

  parameters:
    xdrAuthId:
      name: x-xdr-auth-id
      in: header
      required: false
      description: API Key ID for authentication.
      defaultValue: 1234
      schema:
        type: string
      example: "24"
    authorization:
      name: Authorization
      in: header
      required: true
      description: API Key for authentication.
      schema:
        type: string
      example: "123asdfasdfsadf"
    dashboardId:
      name: dashboardId
      in: path
      required: true
      description: Dashboard ID to look up.
      schema:
        type: string
      example: "dashboard123"
 
security:
  - apiKeyIDAuth: []
    apiKeySecretAuth: []   # <-- No leading dash (-) as this indicates both must be present and NOT either or.

paths:

####################################################################################
#  Dashboards
#     Get all dashboards details
####################################################################################
  /public/v1/dashboards:
    get:
      operationId: X-GetAllDashboardDetails
      description: |
        Palo Alto XSOAR - Get all dashboards details
      examplePrompts:
        - 'Get all Palo Alto XSOAR dashboards'
        - 'Get all Palo Alto XSOAR dashboards details'
        - 'Get all details for Palo Alto XSOAR dashboards'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request, invalid parameters
        "401":
          description: Authentication failed. API Key ID or API Key is incorrect.
        "403":
          description: Access forbidden. Check API Key permissions.

####################################################################################
#  Dashboards
#     Get dashboard details for the specified dashboard
####################################################################################

  /public/v1/dashboards/{dashboardId}:
    get:
      operationId: X-GetDashboardDetails
      description: |
        Palo Alto XSOAR - Get details for specefic dashboard
      examplePrompts:
        - 'Get all Palo Alto XSOAR dashboards'
        - 'Get details for Palo Alto XSOAR dashboard'
      parameters:
        - in: path
          name: dashboardId
          schema:
            type: string
          required: true
          placeholderValue: Dashboard to look up
          description: Dashboard to look up
      responses:
        "200":
          description: OK
        "400":
          description: Bad request, invalid parameters
                    
####################################################################################
#  Incidents
#     Get a specefic incident
####################################################################################


  /public/v1/incident/load/{id}:
    get:
      operationId: X-GetIncident
      description: |
        Palo Alto XSOAR - Get a specific incident
      examplePrompts:
        - 'Get Palo Alto XSOAR incident'
        - 'Get Palo incident'
        - 'Get Palo XSOAR incident'
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          placeholderValue: Incident ID to look up (e.g. 1234)
          description: Incident ID to look up
      responses:
        "200":
          description: OK
        "400":
          description: Bad request, invalid parameters

          
