openapi: 3.0.0

info:
    title: Sentinel Threat Intelligence plugin
    description: Performs API calls on the Sentinel API with OData filters
    version: "v1"
      
servers:
    - url: https://management.azure.com

paths:
    /subscriptions/99005f96-e572-4035-b476-836fd9d83d64/resourceGroups/cybersoc/providers/Microsoft.OperationalInsights/workspaces/cybersoc/providers/Microsoft.SecurityInsights/threatIntelligence/main/queryIndicators:
        post:
            operationId: QueryIndicators            
            description: Lists Threat Intelligence Indicators
            summary: Query Threat Intelligence Indicators
            parameters:
                - in: query
                  name: api-version
                  required: false
                  description: API version
                  schema:
                    type: string
                    default: '2024-03-01'
            requestBody:
            description: Query parameters for fetching threat intelligence indicators
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/QueryIndicatorsRequest'
                  example:
                    keywords: "F2EFE88C8041CCC776859C8B80FB981CF1CF9805B80FC66500738C223A88C713" 
                    sortBy:
                    - itemKey: "lastUpdatedTimeUtc"
                      sortOrder: "descending"
            responses:
                "200":
                    description: OK
                "400":
                    description: Bad request, invalid parameters
